config/routes.rb
Rails.application.routes.draw do

  root to: redirect('w')

  devise_for :ldap_users, :local_users, skip: [:sessions]
  # the login controllers and views are shared for local and ldap users, use :local_user for routes
  devise_scope :local_user do
    get 'login',     to: 'users/sessions#new',     as: 'new_user_session'
    post 'login',    to: 'users/sessions#create',  as: 'user_session'
    delete 'logout', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  # Vypis tyzdnov z daneho setupu, napr. /PSI
  get 'w' => 'weeks#list', as: 'index_week'

    # Vypis otazok z daneho tyzdna, napr. /PSI/3
  get 'w/:week_number' => 'weeks#show'

  # Vrati dalsiu otazku podla odporucaca
  get 'w/:week_number/next' => 'questions#next'

  # Vypis otazky, napr. /PSI/3/16-validacia-a-verifikacia
  get 'w/:week_number/:id' => 'questions#show', as: 'show_learning_object'

  # Docasne takto, postupne sa prejde na namespace aj pre vzdelavacie objekty.
  get 'learning_objects/:id/image' => 'questions#show_image', as: 'show_single_image'

  # Loguje cas straveny na otazke
  post 'log_time' => 'questions#log_time'

  # Opravi otazku a vrati spravnu odpoved
  post 'w/:week_number/:id/evaluate_answers' => 'questions#evaluate'

  # Prepina zobrazovenie odpovedi ku otazkam
  post 'user/toggle-show-solutions' => 'users#toggle_show_solutions'

  post 'feedback' => 'users#send_feedback', as: 'feedback'

  get 'ping' => 'application#ping'

  # Markdown
  post 'markdown/preview' => 'markdown/preview'

  # Administracia
  get 'admin' => 'administrations#index', as: 'administration'

  get 'admin/setup_config/:setup_id' => 'administrations#setup_config', as: 'setup_config'
  get 'admin/setup_config/:setup_id/download_statistics' => 'administrations#download_statistics', as: 'download_statistics'
  post 'admin/setup_config/:setup_id/setup_attributes' => 'administrations#setup_config_attributes', as: 'setup_attributes'
  post 'admin/setup_config/:setup_id/setup_relations' => 'administrations#setup_config_relations', as: 'setup_relations'

  get 'admin/question_concept_config/:course_id' => 'administrations#question_concept_config', as: 'question_concept_config'
  post 'admin/question_concept_config/:course_id/delete_question_concept' => 'administrations#delete_question_concept', as: 'delete_question_concept'
  post 'admin/question_concept_config/:course_id/add_question_concept' => 'administrations#add_question_concept', as: 'add_question_concept'

  get 'admin/questions/:id/feedbacks' => 'administrations#question_feedbacks', as: 'question_feedbacks'
  patch 'admin/feedbacks/:id/accept' => 'administrations#mark_feedback_accepted', as: 'mark_feedback_accepted'
  patch 'admin/feedbacks/:id/reject' => 'administrations#mark_feedback_rejected', as: 'mark_feedback_rejected'
  patch 'admin/feedbacks/:id/show' => 'administrations#mark_feedback_visible', as: 'mark_feedback_visible'
  patch 'admin/feedbacks/:id/hide' => 'administrations#mark_feedback_hidden', as: 'mark_feedback_hidden'
  patch 'admin/feedbacks/:id/anonymize' => 'administrations#mark_feedback_anonymized', as: 'mark_feedback_anonymized'

  get 'admin/courses/:id/questions/next_unresolved' => 'administrations#next_feedback_question', as: 'next_feedback_question'

  # Administracia.
  namespace :admin do

    resources :learning_objects do
      get :index, :new, :edit
      patch :update, :restore
      post :create
      delete :destroy

      resources :answers do
        patch :update, on: :collection
        post :create
        delete :delete
      end

      resources :feedbacks do
        post :create
      end

    end

    resources :concepts do
      get :index, :learning_objects
      post :create
      patch :update
      delete :destroy
      delete :delete_learning_object, on: :collection
    end

    resources :apis do
      get :index
      post :create
    end

  end

  # API
  namespace :api do
    namespace :v1 do
      resources :concepts, only: [:index]
      resources :concept_weeks, only: [:index]
      resources :concepts_learning_objects, only: [:index]
      resources :courses, only: [:index]
      resources :feedbacks, only: [:index]
      resources :learning_objects, only: [:index]
      resources :setups, only: [:index]
      resources :user_to_lo_relations, only: [:index]
      resources :users, only: [:index]
      resources :weeks, only: [:index]

      post 'auth' => 'sessions#create'
      get 'check' => 'sessions#check'
    end
  end

end

app/models/learning_object.rb
# Vzdelavaci objekt.
class LearningObject < ActiveRecord::Base
  acts_as_paranoid

  has_many :answers
  has_many :user_to_lo_relations
  has_many :concepts_learning_objects
  has_many :feedbacks
  has_and_belongs_to_many :concepts, -> { uniq }
  belongs_to :course

  include Exceptions

  # Validacie modelu.
  validates_presence_of :lo_id, presence: true
  validates_presence_of :question_text, presence: true
  validates_presence_of :type, presence: true
  validates_presence_of :difficulty, presence: true

  DIFFICULTY = {
    TRIVIAL:    'trivial',          # I'm too young to die
    EASY:       'easy',             # Hey, not too rough
    MEDIUM:     'medium',           # Hurt me plenty
    HARD:       'hard',             # Ultra-Violence
    IMPOSSIBLE: 'impossible',       # Nightmare!
    UNKNOWN:    'unknown_difficulty'
  }

  validates :difficulty, inclusion: { :in => DIFFICULTY.values }

  TYPE = {
      singlechoicequestion: "SingleChoiceQuestion",
      multichoicequestion: "MultiChoiceQuestion",
      evaluatorquestion: "EvaluatorQuestion"
  }

  validates :type, inclusion: { :in => TYPE.values }

  DIFFICULTY_VALUE = {
      trivial: 0.01,
      easy: 0.25,
      medium: 0.5,
      hard: 0.75,
      impossible: 1,
      unknown_difficulty: 0.5
  }

  IMPORTANCE_VALUE = {
      easy: 0,
      medium: 0.5,
      hard: 1,
      UNKNOWN: 0.5
  }

  # generuje metody z hashu DIFFICULTY, napr. 'learning_object.trivial?'
  LearningObject::DIFFICULTY.values.each do |diff|
    define_method("#{diff}?") do
      self.difficulty == "#{diff}"
    end
  end

  def next(current_user,week_number) # mozno radsej spustit odporucanie.. pri tomto odporucani ani som vsetko nepresla a napisalo ze som na poslednej
    setup = Setup.take
    week = setup.weeks.find_by_number(week_number)

    los = week.learning_objects.first
  end

  def previous(week_number)
    Week.find_by_number(week_number).learning_objects.where('learning_objects.id < ?', self.id).order(id: :desc).first
  end

  def seen_by_user(user_id)
    UserVisitedLoRelation.create(user_id: user_id, learning_object_id: self.id, setup_id: 1)
  end

  # Ziska a vypocita informacie o uspesnosti otazky.
  def successfulness

    stats = UserToLoRelation.where(learning_object: self.id).group(:type).count(:id)
    total = stats['UserSolvedLoRelation'].to_i + stats['UserFailedLoRelation'].to_i

    rate = total > 0 ? ((stats['UserSolvedLoRelation'].to_f / total.to_f)*100).round(2) : 0.0
    { solved: stats['UserSolvedLoRelation'], failed: stats['UserFailedLoRelation'], total: total, rate: rate }

  end

  def url_name
    "#{id}-#{lo_id.parameterize}"
  end

  def link_concept(concept)
    self.concepts << concept unless self.concepts.include?(concept)
  end

  # Overi, ci nova odpoved moze byt oznacena ako spravna.
  def allow_new_correctness?
    if type == "SingleChoiceQuestion"
      answers.each do |answer|
        return false if answer.is_correct
      end
    end
    true
  end

  # Overi, ci nova odpoved moze byt oznacena ako viditelna.
  def allow_new_visibility?
    if type == "EvaluatorQuestion"
      answers.each do |answer|
        return false if answer.visible
      end
    end
    true
  end

  # Overi, ci su korektne nastavenie informacie o odpovediach.
  def validate_answers!

    case type
      when "SingleChoiceQuestion"

        correct_answers = 0
        answers.each do |answer|
          correct_answers += 1 if answer.is_correct
          raise AnswersCorrectnessError if correct_answers > 1
        end

      when "EvaluatorQuestion"

        visible_answers = 0
        answers.each do |answer|
          visible_answers += 1 if answer.visible
          raise AnswersVisibilityError if visible_answers > 1
        end

      else
    end

  end

  # Zistenie ci ma otazka novy feedback, ktory pouzivatel nevidel
  def has_new_feedback?(last_interaction, last_comment)
    self.last_feedback_time.present? && last_interaction.present? &&
        last_interaction < self.last_feedback_time && self.last_feedback_time != last_comment
  end

  # Zistenie ci je posledna interakcia pouzivatela s otazkou vyriesenie otazky
  def done?(done_time, failed_time)
    !done_time.nil? && (failed_time.nil? || done_time > failed_time)
  end

  # Zistenie ci je posledna interakcia pouzivatela s otazkou nevyriesenie otazky
  def failed?(done_time, failed_time)
    !failed_time.nil? && (done_time.nil? || done_time < failed_time)
  end

  # Zistenie ci pouzivatel otazku iba videl a zatial ju neriesil
  def only_seen?(views_time, done_time, failed_time)
    views_time.present? && done_time.nil? && failed_time.nil?
  end

  # Prva navratova hodnota: status danej otazky - vyriesena, nevyriesena, iba videna
  # Druha navratova hodnota: informacia o tom ci ma otazka nejaky novy komentar, ktory user nevidel
  def get_status(los_info)
    current_lo_info = los_info.find {|r| r["result_id"] == self.id.to_s}
    status = ""
    has_new = false

    unless current_lo_info.nil?
      views = current_lo_info['last_visited_time']
      done = current_lo_info['last_solved_time']
      failed = current_lo_info['last_failed_time']
      last_interaction = current_lo_info['last_interaction_time']
      last_comment = current_lo_info['last_user_comment']

      if only_seen?(views, done, failed)
        status = "seen"
      elsif done?(done, failed)
        status = "done"
      elsif failed?(done, failed)
        status = "problem"
      end

      has_new_comment = has_new_feedback?(last_interaction, last_comment)
    end

    return status, has_new_comment
  end

end

app/controllers/admin/learning_objects_controller.rb
module Admin
  # Umoznuje spravovat vzdelavacie objekty.
  class LearningObjectsController < BaseController

    before_filter :get_course, only: [:index, :new, :create]

    # Zobrazenie zoznamu uloh.
    def index
      @questions = @course.learning_objects.eager_load(:answers)

      feedback_new_count = Feedback.where(accepted: nil).where.not(learning_object_id: nil).count
      feedback_all_aggs = Feedback.select("learning_object_id").group(:learning_object_id).count
      feedback_new_aggs = feedback_new_count > 0 ? Feedback.select("learning_object_id").where(accepted: nil).group(:learning_object_id).count : {}
      @feedbacks = {
          all_aggs: feedback_all_aggs,
          new_aggs: feedback_new_aggs,
          new_count: feedback_new_count
      }
    end

    # Vytvorenie noveho vzdelavacieho objektu.
    def new
      @learning_object = LearningObject.new
    end

    # Ulozenie noveho vzdelavacieho objektu.
    def create
      begin
        learning_object_params = params.require(:learning_object).permit(:lo_id, :question_text, :type, :difficulty)
        @learning_object = @course.learning_objects.new(learning_object_params)
        @learning_object.save!
        redirect_to edit_admin_learning_object_path(@learning_object), notice: t('admin.questions.texts.created')
      rescue ActiveRecord::RecordInvalid
        flash[:notice] = t('global.texts.please_fill_in')
        render 'new'
      end
    end

    # Vykresli formular na upravenie vzdelavacieho objektu.
    def edit
      @learning_object = LearningObject.find(params[:learning_object_id])
      @answers = @learning_object.answers
      @feedback_new_count = Feedback.where(accepted: nil).where.not(learning_object_id: nil).count
    end

    # Aktualizuje informacie o vzdelavacom objekte.
    def update
      begin
        learning_object_params = params.require(:learning_object).permit(:lo_id, :question_text, :difficulty)
        @learning_object = LearningObject.find(params[:learning_object_id])
        @learning_object.update!(learning_object_params)
        redirect_to edit_admin_learning_object_path(@learning_object), notice: t('global.texts.updated')
      rescue ActiveRecord::RecordInvalid
        flash[:notice] = t('global.texts.please_fill_in')
        render 'edit'
      end
    end

    # Obnovenie odstraneneho vzdelavacieho objektu.
    def restore
      LearningObject.restore(params[:learning_object_id])
      lo = LearningObject.find(params[:learning_object_id])
      redirect_to admin_learning_objects_path(course: lo.course_id), notice: t('admin.questions.texts.restored')
    end

    # Obnovi otazky.
    def destroy
      lo = LearningObject.find(params[:id])
      lo.destroy!
      redirect_to admin_learning_objects_path(course: lo.course_id), notice: t('admin.questions.texts.deleted')
    end

    private
    def get_course
      begin
        @course = Course.find(params[:course])
      rescue ActiveRecord::RecordNotFound
        redirect_to administration_path
      end
    end

  end
end

app/controllers/api/v1/learning_objects_controller.rb
class Api::V1::LearningObjectsController < Api::V1::BaseController

  def index
    render json: { list: LearningObject.all }, each_serializer: Api::V1::LearningObjectSerializer
  end

end

app/views/admin/learning_objects/_answers.html.erb
<div class="row">

  <div class="col-lg-12" id="answer-settings-col">
    <%= form_tag admin_learning_object_answers_path(learning_object_id: @learning_object.id), method: :patch do %>

        <div class="admin">

          <p><strong><%= t('activerecord.attributes.learning_object.question_text') %>:</strong>
            <%= @learning_object.question_text %></p>

          <table class="answers-table">
            <thead>
            <tr>
              <th class="answers-table-id">ID</th>
              <th>Text odpovede</th>
              <th class="answers-table-tools">Možnosti</th>
            </tr>
            </thead>
            <tbody>
            <% @learning_object.answers.force_all.order('answers.id').each do |a|%>
                <tr class="<%= 'hidden' unless a.visible? %>">
                  <td class="answers-table-id"><%= a.id %></td>
                  <td>
                    <% if a.learning_object.type == "EvaluatorQuestion" %>
                        <%= text_area_tag "edit_answer_text_#{a.id}", a.answer_text, class: "question-answer-area" %>
                    <% else %>
                        <%= text_field_tag "edit_answer_text_#{a.id}", a.answer_text, class: "question-answer" %>
                    <% end %>
                  </td>
                  <td class="answers-table-tools">
                    <% unless a.learning_object.type == "EvaluatorQuestion" %>
                        <%= check_box_tag("correct_answer_#{a.id}", 1, a.is_correct, class: 'icon', data: { type: 'correctness' }) %>
                        <%= label_tag("correct_answer_#{a.id}", "<i class=\"icon-checkbox\"></i>".html_safe, title: 'Správnosť odpovede', data: { toggle: 'tooltip' }) %>
                    <% end %>
                    <%= check_box_tag("visible_answer_#{a.id}", 1, a.visible, class: 'icon', data: { type: 'visibility' }) %>
                    <%= label_tag("visible_answer_#{a.id}", "<i class=\"icon-checkbox icon-eyebox\"></i>".html_safe, title: 'Viditeľnosť odpovede', data: { toggle: 'tooltip' }) %>
                    <%= link_to(fa_icon(:trash), admin_learning_object_answer_path(id: @learning_object.id, answer_id: a.id),
                                method: :delete,
                                class: 'danger',
                                data: { toggle: 'tooltip', confirm: t('admin.answers.questions.remove') },
                                title: t('global.links.remove')) %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>

          <%= submit_tag t('global.links.save_changes'), class: :btn, data: { disable_with: t('global.texts.saving') } %>
          <%= button_tag t('global.links.discard_changes'), class: :btn, type: :reset %>

        </div>

    <% end %>

  </div>
  <div class="col-lg-4" id="answer-feedback-col">
    <div id="feedback-widget" class="content-widget">

      <h3>Nová spätná väzba</h3>

      <ul class="mini-list">
      </ul>

    </div>
  </div>

</div>

<%= form_for Answer.new, url: { controller: 'admin/answers', action: 'create' }, method: :post do |f| %>

    <div class="admin">
      <h3>Pridanie novej odpovede</h3> <br/>
      <%= f.label :answer_text, "Zadaj nový text odpovede:" %>
      <%= f.text_field :answer_text, placeholder: "Text odpovede", class: 'simple-text' %>
      <span class="options-label">Možnosti:</span>
      <% unless @learning_object.type == "EvaluatorQuestion" %>
          <%= f.check_box(:is_correct, { checked: @learning_object.allow_new_correctness? , class: 'icon' }, 1) %>
          <%= f.label(:is_correct, "<i class=\"icon-checkbox\"></i>".html_safe, class: :inline, title: 'Správnosť odpovede', data: { toggle: 'tooltip' }) %>
          &nbsp;&nbsp;
      <% end %>
      <%= f.check_box(:visible_answer, { checked: @learning_object.allow_new_visibility?, class: 'icon' }, 1) %>
      <%= f.label(:visible_answer, "<i class=\"icon-checkbox icon-eyebox\"></i>".html_safe, class: :inline, title: 'Viditeľnosť odpovede', data: { toggle: 'tooltip' }) %>
      <div class="form-buttons">
        <%= f.submit value: "Pridať odpoveď", data: { disable_with: t('global.texts.saving') } %>
      </div>
    </div>

<% end %>

app/views/admin/learning_objects/edit.html.erb
<nav>
  <div class="admin-nav">
    <h2><i data-toggle="tooltip" data-placement="right" title="<%= t("admin.questions.labels.types.#{@learning_object.type.downcase}") %>" class="icon-<%=
      case @learning_object.type
        when "SingleChoiceQuestion"
          'radio-checked'
        when "MultiChoiceQuestion"
          'checkbox-checked'
        when "EvaluatorQuestion"
          'sliders'
      end %>"></i><%= @learning_object.id %> : <%= @learning_object.lo_id %></h2>
    <%= link_to "#{fa_icon('chevron-left')} #{t('admin.questions.links.back_to_management')}".html_safe,
                admin_learning_objects_path(course: @learning_object.course_id), class: 'admin-nav-button' %>
  </div>
</nav>

<hr class="nav-offset">

<%= render 'administrations/feedbacks_banner', feedbacks_new_count: @feedback_new_count, course: @learning_object.course, lite: true %>

<div class="container">

  <div class="tabs">

    <ul id="editor-tabs" class="tablist" role="tablist">
      <li class="active"><a href="#" data-target="#question-settings" role="tab" id="question-tab" data-toggle="tab">Nastavenia otázky</a></li>
      <li><a href="#" data-target="#answer-settings" role="tab" id="answer-tab" data-toggle="tab">Odpovede</a></li>
      <li><a href="#" data-target="#feedbacks" role="tab" id="feedback-tab" data-toggle="tab">Spätná väzba<span id="feedback-not-reviewed-count"></span></a></li>
      <li><a href="#" data-target="#question-preview" role="tab" id="question-preview-tab" data-toggle="tab">Náhľad</a></li>
      <li class="icon"><%= link_to(fa_icon(:trash),
                                         admin_learning_object_path(id: @learning_object.id),
                                         class: 'delete-lo',
                                         method: :delete,
                                         data: {
                                             confirm: 'Naozaj chcete odstrániť tento vzdelávací objekt?',
                                             toggle: :tooltip
                                         },
                                         title: t('global.links.remove')) %></li>

      <li class="icon"><%= link_to(fa_icon(:tag),
                                         question_concept_config_path(@learning_object.course_id, anchor: "question#{@learning_object.id}"),
                                         data: { toggle: :tooltip },
                                         title: t('admin.questions.links.set_concepts')) %></li>
    </ul>

    <div id="editor-tabs-content" class="tab-content is-first">

      <div role="tabpanel" class="tab-pane active" id="question-settings">

        <%= form_for @learning_object, as: :learning_object,
                                       url: { controller: 'admin/learning_objects',
                                              action: :update },
                                       method: :patch do |f| %>

            <div class="admin">

              <div class="form-group">

                <dl class="dl-horizontal">
                  <dt><%= f.label :lo_id, t('activerecord.attributes.learning_object.lo_id') %></dt>
                  <dd><%= f.text_field :lo_id, class: "question_text_field" %></dd>

                  <dt><%= f.label :question_text, t('activerecord.attributes.learning_object.question_text') %></dt>
                  <dd><%= f.text_area :question_text, class: "question_text_field" %></dd>

                  <dt><%= f.label :type, t('activerecord.attributes.learning_object.type') %></dt>
                  <dd><%= t("admin.questions.labels.types.#{@learning_object.type.downcase}") %></dd>

                  <dt><%= f.label :difficulty, t('activerecord.attributes.learning_object.difficulty') %></dt>
                  <dd><%= f.select(:difficulty, options_for_select(LearningObject::DIFFICULTY.map { |id, difficulty|
                    [t("admin.questions.labels.difficulties.#{difficulty}"), difficulty]
                  }, @learning_object.difficulty), class: 'form-control') %></dd>

                  <dt><%= f.label :external_reference, t('admin.questions.labels.external_reference') %></dt>
                  <dd><%= @learning_object.external_reference || '-' %></dd>

                  <dt><%= label_tag t('admin.questions.labels.successfulness') %></dt>
                  <% successfulness = @learning_object.successfulness %>
                  <dd><%= "#{successfulness[:rate]} % (#{successfulness[:solved]} úspešných z #{successfulness[:total]})" %></dd>

                  <dt></dt>
                  <dd>
                    <%= submit_tag t('global.links.save_changes'), class: :btn, data: { disable_with: t('global.texts.saving') } %>
                    <%= button_tag t('global.links.discard_changes'), class: :btn, type: :reset %>
                  </dd>
                </dl>

              </div>

            </div>

        <% end %>

      </div>

      <div role="tabpanel" class="tab-pane" id="answer-settings">
        <%= render 'answers' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="feedbacks">
        <%= render 'feedbacks' %>
      </div>

      <div role="tabpanel" class="tab-pane" id="question-preview">
        <%= render 'questions/question_core', hide_question_options: true, learning_object: @learning_object %>
      </div>

    </div>

  </div>

</div>

<script type="text/javascript">
  $(function(){

    Slider.setupEvaluatorSlider();

    // Zapnutie markdownu.
    new MarkdownPreview($('#learning_object_question_text'), {
      className: 'admin-markdown-textarea admin-markdown-edit-textarea',
      outerClassName: 'admin-markdown-preview'
    });
    $('.question-answer-area').each(function() {
      new MarkdownPreview($(this), { autofix: true, className: 'admin-markdown-textarea', outerClassName: 'admin-markdown-preview' });
    });

    var tabs = $('#editor-tabs').find('li:not(.icon)').find('a');
    tabs.click(function (e) {
      set_tab(tabs, $(this));
      e.preventDefault();
      e.stopImmediatePropagation();
    });

    if (location.hash.length > 0) {
      set_tab(tabs, tabs.filter('[data-target="'+location.hash+'"]'));
    }

    Admin.currentLoId = <%= @learning_object.id %>;
    Admin.fetchFeedback();
    turbolinksSetInterval(function(){
      Admin.fetchFeedback();
    }, 30000);

    <%# Overovanie korektnosti odpovedi. %>
    <% if @learning_object.type == "SingleChoiceQuestion" %>$('input[data-type="correctness"]').change(function(){ Admin.verifySingleChoice($(this)); });<% end %>
    <% if @learning_object.type == "EvaluatorQuestion" %>$('input[data-type="visibility"]').change(function(){ Admin.verifyEvaluator($(this)); });<% end %>

  });

  function set_tab(tabs, tab) {

    var firstTab = tabs.first();

    if (history.pushState) {
      history.pushState(null, null, $(tab).attr('data-target'));
    }
    else {
      location.hash = $(tab).attr('data-target');
    }

    $(tab).tab('show');
    if ($(tab).attr('id') == firstTab.attr('id')) {
      $('#editor-tabs-content').addClass('is-first');
    }
    else {
      $('#editor-tabs-content').removeClass('is-first');
    }

  }
</script>

<%# Sablona pre polozku feedback widgetu (doT.js). %>
<div id="feedback-widget-template" style="display: none">
  <li class="list-item{{?it.accepted == null}} list-item-highlighted{{?}}" data-feedback-id="{{=it.id}}">
    <div class="content">{{=it.message}}</div>
    <div class="tools">
      {{?it.widget}}
        <%= link_to "Vyriešený", mark_feedback_accepted_path('FEEDBACK_ID'), remote: true, method: :patch %>
        &nbsp;&bull;&nbsp;
        <%= link_to "Neriešený", mark_feedback_rejected_path('FEEDBACK_ID'), remote: true, method: :patch %>
        &nbsp;&bull;&nbsp;
        {{?it.visible}}
        <%= link_to "Skryť", mark_feedback_hidden_path('FEEDBACK_ID'), remote: true, method: :patch,
                    title: 'Skryť komentár zo stránky otázky',
                    data: { toggle: "tooltip" } %>
        {{??}}
        <%= link_to "Zobraziť", mark_feedback_visible_path('FEEDBACK_ID'), remote: true, method: :patch,
                    title: 'Zobraziť komentár zo stránky otázky',
                    data: { toggle: "tooltip" } %>
        {{?}}
      {{??}}
        {{?it.accepted == null}}
        <span class="status"><i class="icon-star"></i> Nový</span>
        {{?? it.accepted == true}}
        <span class="status status-success"><i class="icon-checkbox-checked"></i> Vyriešený</span>
        {{??}}
        <span class="status status-danger"><i class="icon-cancel-circled"></i> Neriešený</span>
        {{?}}
        {{?it.visible == true}}
        <span class="status status-success"><i class="icon-seen"></i> Viditeľný</span>
        {{??}}
        <span class="status status-danger"><i class="icon-eye-off"></i> Skrytý</span>
        {{?}}
        {{?it.accepted != true}}
        &nbsp;&bull;&nbsp;
        <%= link_to "Označiť ako vyriešený", mark_feedback_accepted_path('FEEDBACK_ID'), remote: true, method: :patch %>
        {{?}}
        {{?it.accepted != false}}
        &nbsp;&bull;&nbsp;
        <%= link_to "Označiť ako neriešený", mark_feedback_rejected_path('FEEDBACK_ID'), remote: true, method: :patch %>
        {{?}}
        &nbsp;&bull;&nbsp;
        {{?it.visible == true}}
        <%= link_to "Skryť", mark_feedback_hidden_path('FEEDBACK_ID'), remote: true, method: :patch,
                    title: 'Skryť komentár zo stránky otázky',
                    data: { toggle: "tooltip" } %>
        {{??}}
        <%= link_to "Zobraziť", mark_feedback_visible_path('FEEDBACK_ID'), remote: true, method: :patch,
                    title: 'Zobraziť komentár zo stránky otázky',
                    data: { toggle: "tooltip" } %>
        {{?}}
      {{?}}
    </div>

    {{?it.user_verified}}
    <div class="meta">{{=it.fullname}}
      {{?it.anonymous}}
      (<%= link_to t('feedbacks.labels.show_name'), mark_feedback_anonymized_path('FEEDBACK_ID', anonymized: false), remote: true, method: :patch %>),
      {{??}}
      (<%= link_to t('feedbacks.labels.hide_name'), mark_feedback_anonymized_path('FEEDBACK_ID', anonymized: true), remote: true, method: :patch %>),
      {{?}}
      {{=it.time}}</div>
    {{??}}
    <div class="meta">{{=it.fullname}}, {{=it.time}}</div>
    {{?}}

  </li>
</div>