config/routes.rb
Rails.application.routes.draw do

  root to: redirect('w')

  devise_for :ldap_users, :local_users, skip: [:sessions]
  # the login controllers and views are shared for local and ldap users, use :local_user for routes
  devise_scope :local_user do
    get 'login',     to: 'users/sessions#new',     as: 'new_user_session'
    post 'login',    to: 'users/sessions#create',  as: 'user_session'
    delete 'logout', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  # Vypis tyzdnov z daneho setupu, napr. /PSI
  get 'w' => 'weeks#list', as: 'index_week'

    # Vypis otazok z daneho tyzdna, napr. /PSI/3
  get 'w/:week_number' => 'weeks#show'

  # Vrati dalsiu otazku podla odporucaca
  get 'w/:week_number/next' => 'questions#next'

  # Vypis otazky, napr. /PSI/3/16-validacia-a-verifikacia
  get 'w/:week_number/:id' => 'questions#show', as: 'show_learning_object'

  # Docasne takto, postupne sa prejde na namespace aj pre vzdelavacie objekty.
  get 'learning_objects/:id/image' => 'questions#show_image', as: 'show_single_image'

  # Loguje cas straveny na otazke
  post 'log_time' => 'questions#log_time'

  # Opravi otazku a vrati spravnu odpoved
  post 'w/:week_number/:id/evaluate_answers' => 'questions#evaluate'

  # Prepina zobrazovenie odpovedi ku otazkam
  post 'user/toggle-show-solutions' => 'users#toggle_show_solutions'

  post 'feedback' => 'users#send_feedback', as: 'feedback'

  get 'ping' => 'application#ping'

  # Markdown
  post 'markdown/preview' => 'markdown/preview'

  # Administracia
  get 'admin' => 'administrations#index', as: 'administration'

  get 'admin/setup_config/:setup_id' => 'administrations#setup_config', as: 'setup_config'
  get 'admin/setup_config/:setup_id/download_statistics' => 'administrations#download_statistics', as: 'download_statistics'
  post 'admin/setup_config/:setup_id/setup_attributes' => 'administrations#setup_config_attributes', as: 'setup_attributes'
  post 'admin/setup_config/:setup_id/setup_relations' => 'administrations#setup_config_relations', as: 'setup_relations'

  get 'admin/question_concept_config/:course_id' => 'administrations#question_concept_config', as: 'question_concept_config'
  post 'admin/question_concept_config/:course_id/delete_question_concept' => 'administrations#delete_question_concept', as: 'delete_question_concept'
  post 'admin/question_concept_config/:course_id/add_question_concept' => 'administrations#add_question_concept', as: 'add_question_concept'

  get 'admin/questions/:id/feedbacks' => 'administrations#question_feedbacks', as: 'question_feedbacks'
  patch 'admin/feedbacks/:id/accept' => 'administrations#mark_feedback_accepted', as: 'mark_feedback_accepted'
  patch 'admin/feedbacks/:id/reject' => 'administrations#mark_feedback_rejected', as: 'mark_feedback_rejected'
  patch 'admin/feedbacks/:id/show' => 'administrations#mark_feedback_visible', as: 'mark_feedback_visible'
  patch 'admin/feedbacks/:id/hide' => 'administrations#mark_feedback_hidden', as: 'mark_feedback_hidden'
  patch 'admin/feedbacks/:id/anonymize' => 'administrations#mark_feedback_anonymized', as: 'mark_feedback_anonymized'

  get 'admin/courses/:id/questions/next_unresolved' => 'administrations#next_feedback_question', as: 'next_feedback_question'

  # Administracia.
  namespace :admin do

    resources :learning_objects do
      get :index, :new, :edit
      patch :update, :restore
      post :create
      delete :destroy

      resources :answers do
        patch :update, on: :collection
        post :create
        delete :delete
      end

      resources :feedbacks do
        post :create
      end

    end

    resources :concepts do
      get :index, :learning_objects
      post :create
      patch :update
      delete :destroy
      delete :delete_learning_object, on: :collection
    end

    resources :apis do
      get :index
      post :create
    end

  end

  # API
  namespace :api do
    namespace :v1 do
      resources :concepts, only: [:index]
      resources :concept_weeks, only: [:index]
      resources :concepts_learning_objects, only: [:index]
      resources :courses, only: [:index]
      resources :feedbacks, only: [:index]
      resources :learning_objects, only: [:index]
      resources :setups, only: [:index]
      resources :user_to_lo_relations, only: [:index]
      resources :users, only: [:index]
      resources :weeks, only: [:index]

      post 'auth' => 'sessions#create'
      get 'check' => 'sessions#check'
    end
  end

end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :course
  has_many :concepts_learning_objects
  has_many :concepts_weeks
  has_and_belongs_to_many :weeks
  has_and_belongs_to_many :learning_objects, -> { uniq }

  DUMMY_CONCEPT_NAME = 'DUMMY'

  def question_count
    self.learning_objects.count
  end
end

app/controllers/admin/concepts_controller.rb
module Admin
  # Umoznuje spravovat koncepty.
  class ConceptsController < BaseController

    before_filter :get_course, except: [:destroy, :learning_objects, :delete_learning_object]

    # Vykresli zoznam vsetkych konceptov spolu s moznostou ich upravovat.
    def index
      @concepts = @course.concepts.order('name ASC')
      @concepts_counts = ConceptsLearningObject.where(concept_id: @concepts.pluck(:id)).group('concept_id').count
    end

    # Vytvori novy koncept.
    def create
      @course.concepts.create!(parse_params)
      flash[:notice] = t('admin.concepts.texts.create_success')
      redirect_to :back
    end

    # Aktualizuje informacie o koncepte.
    def update
      Concept.find(params[:id]).update!(parse_params)
      render nothing: true
    end

    # Odstrani koncept.
    def destroy
      Concept.find(params[:id]).destroy!
      render nothing: true
    end

    # Nacita vsetky vzdelavacie objekty pridruzene k danemu konceptu.
    def learning_objects
      render json: ConceptsLearningObject.where(concept_id: params[:concept_id])
                       .eager_load(:learning_object)
                       .pluck('concepts_learning_objects.id, learning_objects.id, learning_objects.lo_id')
                       .map { |learning_object| { id: learning_object[0], lo_id: learning_object[1], name: learning_object[2] } }
    end

    # Odstrani priradenie vzdelavacieho objektu do konceptu.
    def delete_learning_object
      ConceptsLearningObject.find(params[:learning_object_id]).destroy!
      render nothing: true
    end

    private
    def parse_params
      concept_params = params.key?(:concept) ? params[:concept].permit(:name, :pseudo) : params.permit(:name, :pseudo)
      concept_params[:pseudo] = concept_params[:pseudo] == "1"
      concept_params
    end

    def get_course
      begin
        @course = Course.find(params[:course])
      rescue ActiveRecord::RecordNotFound
        redirect_to administration_path
      end
    end

  end
end

app/controllers/api/v1/concepts_controller.rb
class Api::V1::ConceptsController < Api::V1::BaseController

  def index
    render json: { list: Concept.all }, each_serializer: Api::V1::ConceptSerializer
  end

end

app/views/admin/concepts/index.html.erb
<% provide(:title, t('admin.concepts.labels.management')) %>
<nav>
  <div class="admin-nav">
    <h2><%= t('admin.concepts.labels.management') %></h2>
    <%= link_to((fa_icon('user-secret') + t('homescreen.links.admin')).html_safe,
                administration_path, class: 'admin-nav-button') %>
  </div>
</nav>
<hr class="nav-offset">

<div class="concept-buttons" id="concept-buttons-panel" style="display: none">
  <div class="admin">
    <%= link_to(t('global.links.discard_changes'), '', class: 'btn') %>
    <button type="button" class="btn btn-primary" onclick="changes.submit(this);"><%= t('global.links.save_all_changes') %></button>
    <%= t('global.labels.number_of_changes') %>: <span id="concept-buttons-changes-count">0</span>
  </div>
</div>
<div class="concept-loading" style="display: none;">
  <%= t('global.texts.saving') %>
</div>

<div id="concepts-list" class="admin">
  <%= form_for Concept.new, url: admin_concepts_path(course: @course), method: :post do |f| %>
    <div class="concept-item concept-new-item">
      <div class="form-group">
        <%= f.text_field :name, class: 'concept_name', placeholder: t('admin.concepts.labels.name_placeholder') %>
      </div>
      <div class="form-group">
        <%= f.check_box :pseudo, checked: false %>
        <%= f.label :pseudo %>
      </div>
      <div class="form-group">
        <%= f.submit t('admin.concepts.links.create_concept'), data: { disable_with: t('global.texts.saving') } %>
      </div>
    </div>
  <% end %>
  <% @concepts.each do |concept| %>
    <div class="concept-item" id="concept<%= concept.id %>" data-object-id="<%= concept.id %>">
      <div class="form-buttons">
        <button type="button" class="btn" onclick="concept_learning_objects(<%= concept.id %>, '<%= concept.name %>');return false"><i class="fa fa-link"></i> <%= t('activerecord.models.learning_object.other') %> (<%= @concepts_counts.key?(concept.id) ? @concepts_counts[concept.id] : 0 %>)</button>
        <button type="button" class="btn btn-delete" onclick="concept_delete(<%= concept.id %>, '<%= admin_concept_path(concept, method: :delete).html_safe %>');return false"><i class="fa fa-trash"></i></button>
      </div>
      <div class="form-error">
        <span title="<%= t('global.errors.something_went_wrong') %>" data-toggle="tooltip"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></span>
      </div>
      <div class="form-group">
        <span class="concept-id"><%= concept.id %></span>
        <%= text_field_tag "concept_name#{concept.id}", concept.name, class: 'concept_name', data: { attr: :name } %>
      </div>
      <div class="form-group">
        <%= check_box_tag "concept_pseudo#{concept.id}", 1, concept.pseudo, data: { attr: :pseudo } %>
        <%= label_tag "concept_pseudo#{concept.id}", t('admin.concepts.labels.pseudo') %>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  var changes = null;
  $(function(){

    changes = new FormChanges($('.concept-item'), '<%= admin_concept_path(id: '_OBJECT_ID_', course: @course, method: :patch).html_safe %>', 'patch');
    changes.on('change,keyup', function(t){
      // S nejakym elementom manipulujeme alebo zmenil hodnotu.
      $('#concept-buttons-panel').show();
      $('#concept-buttons-changes-count').html(t.getChangesCount());
      $('#concept'+data.id).removeClass('concept-item-error');
    }).on('updateStarted', function(){
      // Zaciatok ukladania.
      NProgress.start();
      $('.concept-item').removeClass('concept-item-error');
      $('#concept-buttons-panel').hide();
      $('.concept-loading').show();
      $('#concepts-list').fadeTo(250, 0.2);
    }).on('updateNext', function(t){
      // Preslo ulozenie polozky.
      NProgress.set(t.getQueueStatus());
    }).on('updateFinished', function(t, stats){
      // Preslo ulozenie vsetkych poloziek.
      if (stats.errors > 0) {
        Alert.success("<%= t('admin.concepts.errors.changes_partially_saved') %>");
        $('#concept-buttons-panel').show();
        $('#concept-buttons-changes-count').html(t.getChangesCount());
      }
      else {
        Alert.success("<%= t('global.texts.updated') %>");
      }
      NProgress.done();
      $('.concept-loading').hide();
      $('#concepts-list').fadeTo(250, 1.0);
    }).on('updateErrored', function(t, data){
      // Nastala chyba pri ukladani polozky.
      $('#concept'+data.id).addClass('concept-item-error');
    });

  });
</script>

<div id="concepts-learning-objects-template" style="display: none">
  <h2>&quot;{{=it.name}}&quot; - <%= t('activerecord.models.learning_object.other') %></h2>
  <div class="concept-learning-objects">
    {{~it.learning_objects :learning_object}}
    <div id="concept-learning-object{{=learning_object.id}}" class="learning-object"><a class="remove" href="#" onclick="concept_lo_delete('{{=learning_object.id}}');return false"><i class="fa fa-trash"></i></a><a target="_blank" href="/admin/learning_objects/{{=learning_object.lo_id}}/edit">{{=learning_object.name}}</a></div>
    {{~}}
  </div>

  <%= link_to("#{t('admin.concepts.links.change_lo_assignment')} <i class=\"fa fa-external-link\" aria-hidden=\"true\"></i>".html_safe,
              question_concept_config_path(course_id: @course.id), class: 'concept-editor-link', target: '_blank') %>
</div>