config/routes.rb
Rails.application.routes.draw do

  root to: redirect('w')

  devise_for :ldap_users, :local_users, skip: [:sessions]
  # the login controllers and views are shared for local and ldap users, use :local_user for routes
  devise_scope :local_user do
    get 'login',     to: 'users/sessions#new',     as: 'new_user_session'
    post 'login',    to: 'users/sessions#create',  as: 'user_session'
    delete 'logout', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  # Vypis tyzdnov z daneho setupu, napr. /PSI
  get 'w' => 'weeks#list', as: 'index_week'

    # Vypis otazok z daneho tyzdna, napr. /PSI/3
  get 'w/:week_number' => 'weeks#show'

  # Vrati dalsiu otazku podla odporucaca
  get 'w/:week_number/next' => 'questions#next'

  # Vypis otazky, napr. /PSI/3/16-validacia-a-verifikacia
  get 'w/:week_number/:id' => 'questions#show', as: 'show_learning_object'

  # Docasne takto, postupne sa prejde na namespace aj pre vzdelavacie objekty.
  get 'learning_objects/:id/image' => 'questions#show_image', as: 'show_single_image'

  # Loguje cas straveny na otazke
  post 'log_time' => 'questions#log_time'

  # Opravi otazku a vrati spravnu odpoved
  post 'w/:week_number/:id/evaluate_answers' => 'questions#evaluate'

  # Prepina zobrazovenie odpovedi ku otazkam
  post 'user/toggle-show-solutions' => 'users#toggle_show_solutions'

  post 'feedback' => 'users#send_feedback', as: 'feedback'

  get 'ping' => 'application#ping'

  # Markdown
  post 'markdown/preview' => 'markdown/preview'

  # Administracia
  get 'admin' => 'administrations#index', as: 'administration'

  get 'admin/setup_config/:setup_id' => 'administrations#setup_config', as: 'setup_config'
  get 'admin/setup_config/:setup_id/download_statistics' => 'administrations#download_statistics', as: 'download_statistics'
  post 'admin/setup_config/:setup_id/setup_attributes' => 'administrations#setup_config_attributes', as: 'setup_attributes'
  post 'admin/setup_config/:setup_id/setup_relations' => 'administrations#setup_config_relations', as: 'setup_relations'

  get 'admin/question_concept_config/:course_id' => 'administrations#question_concept_config', as: 'question_concept_config'
  post 'admin/question_concept_config/:course_id/delete_question_concept' => 'administrations#delete_question_concept', as: 'delete_question_concept'
  post 'admin/question_concept_config/:course_id/add_question_concept' => 'administrations#add_question_concept', as: 'add_question_concept'

  get 'admin/questions/:id/feedbacks' => 'administrations#question_feedbacks', as: 'question_feedbacks'
  patch 'admin/feedbacks/:id/accept' => 'administrations#mark_feedback_accepted', as: 'mark_feedback_accepted'
  patch 'admin/feedbacks/:id/reject' => 'administrations#mark_feedback_rejected', as: 'mark_feedback_rejected'
  patch 'admin/feedbacks/:id/show' => 'administrations#mark_feedback_visible', as: 'mark_feedback_visible'
  patch 'admin/feedbacks/:id/hide' => 'administrations#mark_feedback_hidden', as: 'mark_feedback_hidden'
  patch 'admin/feedbacks/:id/anonymize' => 'administrations#mark_feedback_anonymized', as: 'mark_feedback_anonymized'

  get 'admin/courses/:id/questions/next_unresolved' => 'administrations#next_feedback_question', as: 'next_feedback_question'

  # Administracia.
  namespace :admin do

    resources :learning_objects do
      get :index, :new, :edit
      patch :update, :restore
      post :create
      delete :destroy

      resources :answers do
        patch :update, on: :collection
        post :create
        delete :delete
      end

      resources :feedbacks do
        post :create
      end

    end

    resources :concepts do
      get :index, :learning_objects
      post :create
      patch :update
      delete :destroy
      delete :delete_learning_object, on: :collection
    end

    resources :apis do
      get :index
      post :create
    end

  end

  # API
  namespace :api do
    namespace :v1 do
      resources :concepts, only: [:index]
      resources :concept_weeks, only: [:index]
      resources :concepts_learning_objects, only: [:index]
      resources :courses, only: [:index]
      resources :feedbacks, only: [:index]
      resources :learning_objects, only: [:index]
      resources :setups, only: [:index]
      resources :user_to_lo_relations, only: [:index]
      resources :users, only: [:index]
      resources :weeks, only: [:index]

      post 'auth' => 'sessions#create'
      get 'check' => 'sessions#check'
    end
  end

end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController

  authorize_resource :class => false
  def index
    @setups = Setup.all
    @courses = Course.all
  end

  def setup_config
    @setup = Setup.find(params[:setup_id])
    @concepts = @setup.course.concepts.includes(:weeks).order(:pseudo, :name)
    @weeks = @setup.weeks.order(:number)
  end

  def setup_config_attributes
    @setup = Setup.find(params[:setup_id])
    weeks = @setup.weeks
    week_count = params[:setup][:week_count].to_i
    ActiveRecord::Base.transaction do
      if week_count >= @setup.week_count
        (@setup.week_count+1..week_count).each do |w|
          Week.create!(setup_id: @setup.id, number: w)
        end
      else
          weeks.where(number: week_count+1..@setup.week_count).destroy_all
      end
      @setup.update(params.require(:setup).permit(:week_count, :first_week_at, :show_all))
    end
    redirect_to setup_config_path, :notice => "Úspešne uložené"
  end

  def setup_config_relations
    setup = Setup.find(params[:setup_id])
    relations = params[:relations]
    relations.each do |concept, weeks|
      c = Concept.find(concept)
      w = setup.weeks.find(weeks.keys)
      c.weeks = w
    end
    # clear all concepts with nothing checked
    (setup.course.concepts.all - Concept.find(relations.keys)).each do |c|
      c.weeks = []
    end
    redirect_to setup_config_path, :notice => "Úspešne uložené"
  end

  def download_statistics
    @setup = Setup.find(params[:_setup_id])
    filepath_full = @setup.compute_stats()
    send_file filepath_full
  end

  def question_concept_config
    @course = Course.find(params[:course_id])
    @questions = @course.learning_objects.includes(:answers,:concepts).all
    gon.concepts = @course.concepts.pluck(:name)
  end

  def delete_question_concept
    question = LearningObject.find(params[:question_id])
    Concept.find(params[:concept_id]).learning_objects.delete(question)
  end

  # Pouziva sa pre vzdialene nacitanie spatnej vazby.
  def question_feedbacks
    @question = LearningObject.find_by_id(params[:id])

    list = @question.feedbacks.includes(:user).order(accepted: :desc).order(created_at: :asc).map do |feedback|
      {
          id: feedback.id,
          accepted: feedback.accepted,
          user_verified: feedback.user.verified?,
          anonymous: feedback.anonymous_teacher,
          message: feedback.message,
          fullname: feedback.user.full_name,
          time: feedback.created_at.strftime("%d.%m.%Y %H:%M:%S"),
          visible: feedback.visible
      }
    end

    render json: list
  end

  # Oznaci spatnu vazbu za schvalenu.
  def mark_feedback_accepted
    Feedback.find(params[:id]).update(accepted: true)
    render js: "Admin.fetchFeedback();"
  end

  # Oznaci spatnu vazbu za zamietnutu.
  def mark_feedback_rejected
    Feedback.find(params[:id]).update(accepted: false)
    render js: "Admin.fetchFeedback();"
  end

  # Zobrazi spatnu vazbu (na stranke s otazkou).
  def mark_feedback_visible
    Feedback.find(params[:id]).update(visible: true)
    render js: "Admin.fetchFeedback();"
  end

  # Skryje spatnu vazbu (na stranke s otazkou).
  def mark_feedback_hidden
    Feedback.find(params[:id]).update(visible: false)
    render js: "Admin.fetchFeedback();"
  end

  # Zmeni nastavenia skrytia mena ucitela v spatnej vazbe.
  def mark_feedback_anonymized
    Feedback.find(params[:id]).update(anonymous_teacher: params[:anonymized] == "true")
    render js: "Admin.fetchFeedback();"
  end

  # Ziska nasledujucu otazku (z kurzu), ku ktorej este nebola pridana spatna vazba.
  def next_feedback_question
    @course = Course.find(params[:id])

    unless session.has_key?(:unresoved_feedbacks) && session[:unresoved_feedbacks].any?
      session[:unresoved_feedbacks] = @course.feedbackable_questions
    end

    lo = LearningObject.where(id: session[:unresoved_feedbacks].pop).first
    if lo
      redirect_to(edit_admin_learning_object_path(lo))
    else
      redirect_to(admin_learning_objects_path(course: @course.id))
    end

  end

  def add_question_concept
    if params[:concept_name].empty?
      render nothing: true
      return
    end

    @concept = Course.find(params[:course_id]).concepts.find_by_name(params[:concept_name])
    @question = LearningObject.find(params[:question_id])

    if (not(@concept.nil?)) && (not(@question.concepts.include? @concept))
      @question.concepts << @concept
      return
    end
    render nothing: true
  end

end

app/views/administrations/_concept.html.erb
<div class="concept">
  <%= concept.name %>
  <%= button_tag '<i class="icon-delete"></i>'.html_safe, type: 'button', class: 'concept-delete', data: { question_id: question.id, concept_id: concept.id } %></div>

app/views/administrations/_feedbacks_banner.html.erb
<% if feedbacks_new_count > 0 %>
    <div id="feedback-alert" class="admin<%= ' feedback-lite' if lite %>">
      <%= link_to("Nasledujúca otázka &raquo;".html_safe,
                  next_feedback_question_path(course.id),
                  class: 'action-btn',
                  data: { toggle: :tooltip },
                  title: "Prejsť na otázku s nevyriešenou spätnou väzbou") %>
      <span class="preicon"><%= fa_icon :star %></span>Našli sme <%= feedbacks_new_count %> nových komentárov k otázkam.
      <% unless lite %><%= link_to "Zobraziť iba otázky s novými komentármi &raquo;".html_safe, '', onclick: 'Admin.questionsToggleWithFeedback(this);return false;' %><% end %>
    </div>
<% end %>

app/views/administrations/add_question_concept.js.erb
(function() {
    var rendered = "<%= j render(:partial => 'concept', locals: {concept: @concept, question: @question}) %>";
    $('.concept-list[data-question-id=<%= @question.id %>]').append(rendered);
    Admin.setupConceptDelete();
})();

app/views/administrations/concept_config.html.erb
<nav>
  <div class="admin-nav">
    <h2><%= @course.name %></h2>
    <%= link_to "Administrácia", administration_path, class: 'admin-nav-button' %>
  </div>
</nav>
<hr class="nav-offset">

<div class="admin wide">
  <table id="concept-table">
    <tr>
      <td></td><td></td><th style="vertical-align: middle">Pridaj koncept:</th>
      <td>
        <%= form_tag url_for(add_concept_path), :method => 'post' do %>
            <table>
              <td><%= text_field_tag :add_concept_name, nil, placeholder: "Názov konceptu" %></td>
              <th>Pseudo koncept:</th><td><%= check_box_tag :pseudo_concept %></td>
              <td class="concept-button"><%= submit_tag "Pridaj" %></td>
            </table>
        <% end %>
      </td>
    </tr>
    <tr class="bold_text_row">
      <td class="concept-header">Názov konceptu</td>
      <td class="concept-header">Typ konceptu</td>
      <td class="concept-header">Odstráň koncept</td>
      <td class="concept-header">Editácia konceptu</td>
    </tr>
    <% @concepts.each do |c| %>
      <tr>
        <td>
          <div class="concept-table-cell">
            <%= c.name %>
          </div>
        </td>
        <td>
          <div class="concept-table-cell">
            <% if c.pseudo %>
              Pseudo koncept
            <% else %>
              Skutočný koncept
            <% end %>
          </div>
        </td>
        <td style="align-content: center">
          <%= link_to((button_tag '<i class="icon-delete"></i>'.html_safe, type: 'button', class: 'delete_concept_button'), url_for(delete_concept_path(:concept_id => c.id)), :method => :post)%>
        </td>
        <td>
            <%= form_tag url_for(edit_concept_path(:concept_id => c.id)), :method => 'post' do %>
              <table>
                <td> <%= text_field_tag :edit_concept_name, nil, placeholder: "Nový názov konceptu" %></td>
                <th>Pseudo koncept:</th><td><%= check_box_tag :pseudo_concept %></td>
                <td class="concept-button"><%= submit_tag "Uprav" %></td>
              </table>
            <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/administrations/delete_question_concept.js.erb
(function() {
    $('.concept-delete[data-question-id=<%= params[:question_id] %>][data-concept-id=<%= params[:concept_id] %>]').
    closest('.concept').remove();
})();

app/views/administrations/index.html.erb
<nav>
  <div class="admin-nav">
    <h2>Administrácia</h2>
    <%= link_to((fa_icon('home') + t('homescreen.links.home')).html_safe,
                root_path, class: 'admin-nav-button') %>
  </div>
</nav>
<hr class="nav-offset">

<div class="admin">
  <h3>Nastavenia setupov</h3>
  <ul>
  <% @setups.each do |s| %>
    <li><%= link_to s.name, setup_config_path(s.id), class: "admin-link", id: "setup#{s.id}" %></li>
  <% end %>
  </ul>
</div>

<div class="admin">
  <h3>Nastavenia kurzov</h3>
  <ul class="courses-list">
    <% @courses.each do |c| %>
        <li>
          <%= link_to c.name, question_concept_config_path(c.id), class: "admin-link", id: "concept#{c.id}" %>
          <div class="links">
            <%= link_to 'zmeniť mapovanie konceptov', question_concept_config_path(c.id) %>
            &nbsp;&nbsp;&bull;&nbsp;&nbsp;
            <%= link_to 'upraviť koncepty', admin_concepts_path(course: c) %>
          </div>
        </li>
    <% end %>
  </ul>
</div>

<div class="admin">
  <h3>Správa obsahu otázok</h3>
  <ul>
    <% @courses.each do |c| %>
        <li><%= link_to c.name, admin_learning_objects_path(course: c.id), class: "admin-link", id: "learning-objects#{c.id}" %></li>
    <% end %>
  </ul>
</div>

app/views/administrations/question_concept_config.html.erb
<nav>
  <div class="admin-nav">
    <h2><%= @course.name %></h2>
    <%= link_to((fa_icon('user-secret') + t('homescreen.links.admin')).html_safe,
                administration_path, class: 'admin-nav-button') %>
  </div>
</nav>
<hr class="nav-offset">

<div class="admin wide">
  <table id="question-concept-table">
    <% @questions.each do |q| %>
        <tr id="question<%= q.id %>">
            <td style="width: 40%;">
              <div class="question-concept-table-cell">
                <i class="icon-<%=
                case q.type
                when "SingleChoiceQuestion"
                'radio-checked'
                when "MultiChoiceQuestion"
                'checkbox-checked'
                when "EvaluatorQuestion"
                'sliders'
                end %>"></i>
                  <strong><%= q.lo_id %></strong>
                  <%= q.question_text %>
                  <span class="question-concept-table-answers">
                  <% q.answers.each do |a|
                    if a.is_correct %>
                        <strong>"<%= a.answer_text %>",</strong>
                    <% else %>
                        "<%= a.answer_text %>",
                    <% end %>
                  <% end %>
                </span>
              </div>
            </td>
            <td class="concept-list" data-question-id="<%= q.id %>">
              <% q.concepts.each do |c| %>
                  <%= render partial: 'concept', locals: {concept: c, question: q} %>
              <% end %>
            </td>
            <td nowrap>
              <%= text_field_tag "a", nil, placeholder: 'Pridať koncept', class: 'concept-autocomplete', data: { question_id: q.id } %>
              <%= button_tag '<i class="icon-add"></i>'.html_safe, type: 'button', class: 'concept-add', data: { question_id: q.id } %>
            </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/administrations/setup_config.html.erb
<nav>
   <div class="admin-nav">
    <h2><%= @setup.name %></h2>
     <%= link_to((fa_icon('user-secret') + t('homescreen.links.admin')).html_safe,
                 administration_path, class: 'admin-nav-button') %>
   </div>
</nav>
<hr class="nav-offset">

<div class="admin">
  <h3>Aktivita študentov - Štatistiky</h3>
  <ul><%= link_to "#{@setup.name} Štatistiky aktivity študentov", download_statistics_path(:_setup_id => @setup.id), class: "admin-link" %></ul>
</div>
<div class="admin">
  <h3>Základné nastavenia</h3>
  <%= form_for @setup, url: url_for(setup_attributes_path), html: {method: 'post'} do |s| %>
    <table>
    <tr><th class="th-right">Počet týždňov:</th><td><%= s.text_field :week_count %></td></tr>
    <tr><th class="th-right">Začiatok kurzu:</th><td><%= date_select :setup, :first_week_at %></td></tr>
    <tr><th class="th-right">Zobrazovať všetky týždne:   </th><td><%= s.check_box :show_all %></td></tr>
    </table>
    <%= s.submit "Uložiť" %>
  <% end %>
</div>
<div class="admin">
  <h3>Nastavenia konceptov</h3>
  <%= form_tag url_for(setup_relations_path), method: 'post', id: 'concepts-form' do %>
  <table id="week-concept-table">
    <tr>
      <th>Názov konceptu</th>
      <% @weeks.each do |w| %>
          <th>
            <%= w.number %>
          </th>
      <% end %>
    </tr>
    <% @concepts.each do |c| %>
      <tr>
      <td>
        <%= c.name %> (<%= c.question_count %>)
      </td>
      <% @weeks.each do |w| %>
          <td <%= if w.actual?; 'class="active"'.html_safe; end %>>
            <%= check_box_tag "relations[#{c.id}][#{w.id}]", "1", (w.id.in? c.weeks.map(&:id)), class: "week-concept", 'data-week' => w.id %>
          </td>
      <% end %>
      </tr>
    <% end %>
    <tr>
      <th>Počet otázok</th>
      <% @weeks.each do |w| %>
          <td>
            <%= w.question_count %>
          </td>
      <% end %>
    </tr>
    <tr>
      <th>Nastaviť všetky</th>
      <% @weeks.each do |w| %>
          <td>
            <%= check_box_tag "switch_all", nil, false, class: "switch-all", 'data-week' => w.id %>
          </td>
      <% end %>
    </tr>
  </table>
  <%= submit_tag t('global.links.save_changes') %>
  <% end %>
</div>